[package]
name = "http-health-check"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
hyper.workspace = true
snafu.workspace = true
tracing.workspace = true
